[package]
name = "tiny_regex"
version = "0.1.0"
edition = "2021"

[lib]
name = "tiny_regex"
path = "src/lib.rs"

[[bin]]
name = "tiny_grep"
path = "src/main.rs"

[[bin]]
name = "re_place"
path = "src/re_place.rs"

[dependencies]


[features]
on_the_fly = []